### ISSUE TITLE
关于模板扩展的2个问题及建议

### ISSUE THREAD

**Issue by hainuo** [easysoft/chanzhieps#3]
关于模板的扩展，最近在更新markdown编辑器，发现在处理前台展示时遇到以下问题
1、头部模板使用，在模板中都是使用的include TPL_ROOT ."common/header.html.php"  这种方式导致在扩展的时候，要么复制一份放在当前模块下，要么直接修改公共的header.html.php模板，官方每次更新都会被覆盖一下。
2、扩展模板不区分mobile模板和desktop模板，导致使用手机访问时扩展模板没有对应mobile方式做处理，页面报错或者功能不可用。导致手机端适配出错

鉴于以上两点建议官方对模板采用公共方法getViewFile来引用模板，通过扩展参数ext,mobile或者这ext,desktop来处理适配问题。

**Comment by easysoft** [comment]
以后在蝉知官网论坛讨论即可。
